language: go

go:
  - 1.11
  - 1.12

before_install:
  - sudo apt-get install libgeoip-dev bzr

install:
  - go get gopkg.in/check.v1

script:
  - cd $TRAVIS_BUILD_DIR && go test -gocheck.v
  - go test -gocheck.v -gocheck.b -gocheck.btime=2s
